# ##############################################################################
# OASIS: Open Algebra Software for Inferring Solutions
#
# doxygen.yml
# ##############################################################################

name: Deploy static content to Pages

on:
    push:
        branches: [ "master" ]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        
        steps:
            # Checks out the repository.
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
                submodules: recursive

            # Installs Doxygen and Graphviz on the runner.
          - name: Install Doxygen
            run: |
                sudo apt-get update
                sudo apt-get install -y curl graphviz
                curl -L https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz | tar xzvf -

            # Sets up GitHub Pages.
          - name: Setup GitHub Pages
            uses: actions/configure-pages@v4

            # Generates documentataion using Doxygen.
          - name: Generate documentation
            run: ./doxygen-1.10.0/bin/doxygen

          - name: Copy Big Cat Large
            run: |
                mkdir docs/html/docs
                cp docs/*.png docs/html/docs/

            # Uploads documentation artifacts.
          - name: Upload artifacts
            uses: actions/upload-pages-artifact@v3
            with:
              path: 'docs/html'

            # Deploys to GitHub Pages.
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
