# ##############################################################################
# OASIS: Open Algebra Software for Inferring Solutions
#
# format-cmake.yml
# ##############################################################################

name: Format CMake

on:
    pull_request:
        branches: [ "master" ]

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            # Checks out the repository.
          - name: Checkout repository
            uses: actions/checkout@v3

            # Installs cmakelang.
          - name: Install cmakelang
            run: pip install cmakelang

            # Runs cmake-format on all CMakeLists.txt files.
          - name: Run cmake-format
            run: find . -name CMakeLists.txt -type f -execdir bash -c "cmake-format -i {}" \;

            # Checks for modified files.
          - name: Check for modified files
            id: check-file-modified
            run: echo "files-modified=$(git diff --name-only | wc -l)" >> "$GITHUB_OUTPUT"

            # Commits and pushes changes.
          - name: Commit and push
            if: steps.check-file-modified.outputs.files-modified != 0
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
                gh pr checkout ${{ github.event.pull_request.number }}
                git config user.name "github-actions"
                git config user.email "github-actions@github.com"
                git commit -am "[Actions] Format CMakeLists.txt"
                git push
