name: Valgrind Memory Check

on:
  workflow_run:
    workflows: ["CMake on multiple platforms"]
    types:
      - completed

jobs:
  valgrind-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        c_compiler: [ gcc, clang-17 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-ubuntu-latest-debug-${{ matrix.c_compiler }}
          path: build

      - name: Install Valgrind
        run: sudo apt-get install -y valgrind

      - name: Run Valgrind
        run: |
          cd build
          valgrind --leak-check=full --error-exitcode=1 ctest --build-config Debug