name: Valgrind Memory Check

on:
  workflow_run:
    workflows: ["CMake on multiple platforms"]
    types:
      - completed

jobs:
  valgrind-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        c_compiler: [ gcc, clang-17 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/github-script@v5
        with:
          script: |
            const artifact = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: "{{ matrix.c_compiler }}",
              archive_format: 'zip'
            });
            return artifact.zipball_url;

      - name: Unzip artifact
        run: unzip build/${{ matrix.c_compiler }}.zip -d build

      - name: Install Valgrind
        run: sudo apt-get install -y valgrind

      - name: Run Valgrind
        run: |
          cd build
          valgrind --leak-check=full --error-exitcode=1 ctest --build-config Debug